apiVersion: v1
kind: Service
metadata:
  name: sample-api
  labels:
    app.kubernetes.io/name: sample-api
    app.kubernetes.io/part-of: dissertation-platform
    owner: platform-team
    compliance: baseline
spec:
  selector:
    app: sample-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
