apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dissertation-sample-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ME/dissertation
    targetRevision: HEAD
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: dissertation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
